### ISSUE TITLE
Bug - Janicart One-Way Storage

### ISSUE THREAD

**Issue by Wesreidau** [discordia-space/CEV-Eris#2560] opened 2019-01-09 01:55 UTC
nice ping: BUG: You can put cleaner grenades and bodybags in janicart (the one that holds stuff), but not take them back. (plus you also get pussy wagon keys, but no janicart itself)

**Comment by NanakoAC** [comment] 2019-01-11 21:11
Closing as not a bug. You cannot actually put them in the janicart, you put them into the trashbag, and thats where they go.
These items are currently not supported on the cart. Perhaps they should be, but thats a seperate problem

**Closed by NanakoAC** 2019-01-11 21:11 UTC
Labels: not a bug
