### ISSUE TITLE
Floor tiles do not appear when prying non-standart tiles

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1265] opened 2017-11-28 19:45 UTC
Confirmation is needed

**Comment by NanakoAC** [comment] 2018-09-21 01:45
floor stuff

**Comment by NanakoAC** [comment] 2018-09-27 09:12
hmm, no tiles from AI circuit floor, maybe some others

**Comment by NanakoAC** [comment] 2018-09-27 09:17
duplicate of #476

**Closed by NanakoAC** 2018-09-27 09:17 UTC
Labels: Bug: cause are known, Possibility of bug
