### ISSUE TITLE
[BUG] Camera is unweldeable 

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#4159] opened 2019-11-11 20:49 UTC
You can't weld a camera to the wall because this happens simultaneously once you click on it with welder

![unknown (3)](https://user-images.githubusercontent.com/49165135/68620148-90140e00-04d5-11ea-82a6-d6c240668c1d.png)

**Comment by MadmanMartian** [comment] 2019-11-27 17:01
Unable to reproduce: Was able to wrench and then weld a camera assembly

**Comment by MadmanMartian** [comment] 2019-11-27 17:01
Seems it was fixed in https://github.com/discordia-space/CEV-Eris/pull/4127

**Closed** 2020-01-05 10:35 UTC
