### ISSUE TITLE
[Runtime] Cannot read null.len

### ISSUE THREAD

**Issue by Kurgis** [discordia-space/CEV-Eris#4087] opened 2019-11-01 07:39 UTC
[03:36:02] Skipped 16225 runtimes in icons.dm,572.
[03:36:02] Skipped 16225 runtimes in misc.dm,55.
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
[03:36:07] Runtime in icons.dm,572: Cannot read null.len
  (This error will now be item_flags & SILENT for 10 minutes)
[03:36:07] Runtime in misc.dm,55: Cannot execute null.get free space().
  (This error will now be item_flags & SILENT for 10 minutes)

To say the least, this caused my client to freeze, but not the local server.

**Comment by Kurgis** [comment] 2019-11-01 22:41
Not sure how to replicate.

**Comment by PlinHost** [comment] 2019-11-01 22:57
The issue is still there. Occurs randomly soon after roundstart. Got it after restarting a couple of times. Please reopen.

More info:
```
Runtime in icons.dm,572: Cannot read null.len
  proc name: BlendRGB (/proc/BlendRGB)
  src: null
  call stack:
  BlendRGB(null, "#ffffffff", 0.8)
  the powder pile (/obj/effect/decal/cleanable/reagents/piled): add reagents(/datum/reagents (/datum/reagents))
  /datum/reagents (/datum/reagents): trans to turf(the open space (69,51,4) (/turf/simulated/open), 4.7, 1, 1)
  /datum/reagents (/datum/reagents): trans to(the open space (69,51,4) (/turf/simulated/open), 4.7, 1, 1, 0)
  /datum/reagents (/datum/reagents): splash(the open space (69,51,4) (/turf/simulated/open), 4.7, 1, 1, 0, 60)
  /datum/reagents (/datum/reagents): splash(the power cable (/obj/structure/cable/green), 5.3, 1, 1, 0, 60)
  the smoke (/obj/effect/effect/smoke/chem): Move(the underplating (70,50,4) (/turf/simulated/floor/plating/under), 8, 0, 0, 0)
  the smoke (/obj/effect/effect/smoke/chem): Move(the underplating (70,50,4) (/turf/simulated/floor/plating/under), 9, 0, 0, 0)
  the smoke (/obj/effect/effect/smoke/chem): Move(the underplating (70,50,4) (/turf/simulated/floor/plating/under), 9, 0, 0, 0)
  the smoke (/obj/effect/effect/smoke/chem): Move(the underplating (70,50,4) (/turf/simulated/floor/plating/under), 9, 0, 0, 0)

Runtime in misc.dm,55: Cannot execute null.get free space().
  proc name: add reagents (/obj/effect/decal/cleanable/reagents/proc/add_reagents)
  src: the powder pile (/obj/effect/decal/cleanable/reagents/piled)
  src.loc: the open space (69,51,4) (/turf/simulated/open)
  call stack:
  the powder pile (/obj/effect/decal/cleanable/reagents/piled): add reagents(/datum/reagents (/datum/reagents))
  the powder pile (/obj/effect/decal/cleanable/reagents/piled): add reagents(/datum/reagents (/datum/reagents))
  /datum/reagents (/datum/reagents): trans to turf(the open space (69,51,4) (/turf/simulated/open), 4.7, 1, 1)
  /datum/reagents (/datum/reagents): trans to(the open space (69,51,4) (/turf/simulated/open), 4.7, 1, 1, 0)
  /datum/reagents (/datum/reagents): splash(the open space (69,51,4) (/turf/simulated/open), 4.7, 1, 1, 0, 60)
  /datum/reagents (/datum/reagents): splash(the power cable (/obj/structure/cable/green), 5.3, 1, 1, 0, 60)
  the smoke (/obj/effect/effect/smoke/chem): Move(the underplating (70,50,4) (/turf/simulated/floor/plating/under), 8, 0, 0, 0)
  the smoke (/obj/effect/effect/smoke/chem): Move(the underplating (70,50,4) (/turf/simulated/floor/plating/under), 9, 0, 0, 0)
  the smoke (/obj/effect/effect/smoke/chem): Move(the underplating (70,50,4) (/turf/simulated/floor/plating/under), 9, 0, 0, 0)
  the smoke (/obj/effect/effect/smoke/chem): Move(the underplating (70,50,4) (/turf/simulated/floor/plating/under), 9, 0, 0, 0)
```

**Comment by ACCount12** [comment] 2019-12-17 07:29
Was fixed by me at some point. Reagent piles are still broken as fuck though.

**Closed by ACCount12** 2019-12-17 07:29 UTC
