### ISSUE TITLE
Another storyteller vote bug

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#2080] opened 2018-09-30 07:24 UTC
BUG: the server starts a storyteller vote after failing to select a captain/technomancer.

It is not supposed to be so

**Comment by NanakoAC** [comment] 2018-10-05 06:17
It is supposed to be so.
The crew requirements are decided on a per-storyteller basis. If the chosen storyteller fails to find the crew it needs, then it asks you to pick a different one
Working as intended, closing

**Closed by NanakoAC** 2018-10-05 06:17 UTC
Labels: Minor, not a bug
