### ISSUE TITLE
IH hardsuit magboots don't work

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2521] opened 2019-01-07 23:51 UTC

**Comment by Wesreidau** [comment] 2019-01-14 21:54
Exult voidsuit magboots do not appear to work either. In fact I have had really no luck with magboots thus far.

**Comment by soslow4u** [comment] 2019-04-08 04:14
Related to #3282, cant reproduce it now. Fixed in #3284

**Closed** 2019-04-08 12:07 UTC
